
export interface DistrictCodeInfo {
  region: string;
  district: string;
  municipality: string;
}

export const GHANA_POST_DISTRICT_CODES: Record<string, DistrictCodeInfo> = {
  "A2": { region: "Ashanti Region", district: "Adansi North", municipality: "Adansi North" },
  "A3": { region: "Ashanti Region", district: "Adansi South", municipality: "Adansi South" },
  "A4": { region: "Ashanti Region", district: "Bosome Freho", municipality: "Bosome Freho" },
  "A5": { region: "Ashanti Region", district: "Adansi Asokwa", municipality: "Adansi Asokwa" },
  "A6": { region: "Ashanti Region", district: "Offinso North", municipality: "Offinso North" },
  "A7": { region: "Ashanti Region", district: "Offinso South", municipality: "Offinso South" },
  "A8": { region: "Ashanti Region", district: "Ahafo Ano South East", municipality: "Ahafo Ano South East" },
  "AA": { region: "Ashanti Region", district: "Asante Akim South", municipality: "Asante Akim South" },
  "AAF": { region: "Ashanti Region", district: "Akrofuom", municipality: "Akrofuom" },
  "AAK": { region: "Ashanti Region", district: "Afigya Kwabre North", municipality: "Afigya Kwabre North" },
  "AAM": { region: "Ashanti Region", district: "Amansie South", municipality: "Amansie South" },
  "AAS": { region: "Ashanti Region", district: "Asokwa", municipality: "Asokwa" },
  "AAT": { region: "Ashanti Region", district: "Atwima Nwabiagya North", municipality: "Atwima Nwabiagya North" },
  "AB": { region: "Ashanti Region", district: "Bekwai", municipality: "Bekwai" },
  "AC": { region: "Ashanti Region", district: "Asante Akim Central", municipality: "Asante Akim Central" },
  "AD": { region: "Ashanti Region", district: "Kwabre East", municipality: "Kwabre East" },
  "AE": { region: "Ashanti Region", district: "Ejisu", municipality: "Ejisu" },
  "AF": { region: "Ashanti Region", district: "Afigya Kwabre", municipality: "Afigya Kwabre" },
  "AG": { region: "Ashanti Region", district: "Atwima Kwanwoma", municipality: "Atwima Kwanwoma" },
  "AH": { region: "Ashanti Region", district: "Atwima Nwabiagya", municipality: "Atwima Nwabiagya" },
  "AI": { region: "Ashanti Region", district: "Atwima Mponua", municipality: "Atwima Mponua" },
  "AJ": { region: "Ashanti Region", district: "Ejura-Sekyedumase", municipality: "Ejura-Sekyedumase" },
  "AK": { region: "Ashanti Region", district: "Kumasi", municipality: "Kumasi" },
  "AKW": { region: "Ashanti Region", district: "Kwadaso", municipality: "Kwadaso" },
  "AL": { region: "Ashanti Region", district: "Juaben", municipality: "Juaben" },
  "AM": { region: "Ashanti Region", district: "Mampong", municipality: "Mampong" },
  "AN": { region: "Ashanti Region", district: "Asante Akim North", municipality: "Asante Akim North" },
  "AO": { region: "Ashanti Region", district: "Obuasi", municipality: "Obuasi" },
  "AOE": { region: "Ashanti Region", district: "Obuasi East", municipality: "Obuasi East" },
  "AOK": { region: "Ashanti Region", district: "Oforikrom", municipality: "Oforikrom" },
  "AOT": { region: "Ashanti Region", district: "Old Tafo", municipality: "Old Tafo" },
  "AP": { region: "Ashanti Region", district: "Sekyere Afram Plains", municipality: "Sekyere Afram Plains" },
  "AQ": { region: "Ashanti Region", district: "Sekyere Central", municipality: "Sekyere Central" },
  "AR": { region: "Ashanti Region", district: "Sekyere East", municipality: "Sekyere East" },
  "AS": { region: "Ashanti Region", district: "Asokore Mampong", municipality: "Asokore Mampong" },
  "ASU": { region: "Ashanti Region", district: "Suame", municipality: "Suame" },
  "AT": { region: "Ashanti Region", district: "BOSOMTWE", municipality: "BOSOMTWE" },
  "AU": { region: "Ashanti Region", district: "Sekyere Kumawu", municipality: "Sekyere Kumawu" },
  "AV": { region: "Ashanti Region", district: "Amansie Central", municipality: "Amansie Central" },
  "AW": { region: "Ashanti Region", district: "Amansie West", municipality: "Amansie West" },
  "AX": { region: "Ashanti Region", district: "Ahafo Ano North", municipality: "Ahafo Ano North" },
  "AY": { region: "Ashanti Region", district: "Ahafo Ano South West", municipality: "Ahafo Ano South West" },
  "AZ": { region: "Ashanti Region", district: "Sekyere South", municipality: "Sekyere South" },
  "BA": { region: "Bono Region", district: "Banda", municipality: "Banda" },
  "BB": { region: "Bono Region", district: "Berekum East", municipality: "Berekum East" },
  "BC": { region: "Bono Region", district: "Berekum West", municipality: "Berekum West" },
  "BD": { region: "Bono Region", district: "Dormaa Central", municipality: "Dormaa Central" },
  "BE": { region: "Bono Region", district: "Dormaa East", municipality: "Dormaa East" },
  "BF": { region: "Bono Region", district: "Dormaa West", municipality: "Dormaa West" },
  "BI": { region: "Bono Region", district: "Jaman South", municipality: "Jaman South" },
  "BJ": { region: "Bono Region", district: "Jaman North", municipality: "Jaman North" },
  "BS": { region: "Bono Region", district: "Sunyani", municipality: "Sunyani" },
  "BW": { region: "Bono Region", district: "Wenchi", municipality: "Wenchi" },
  "BY": { region: "Bono Region", district: "Sunyani West", municipality: "Sunyani West" },
  "BZ": { region: "Bono Region", district: "Tain", municipality: "Tain" },
  "CA": { region: "Central Region", district: "Abura Asebu Kwamankese", municipality: "Abura Asebu Kwamankese" },
  "CB": { region: "Central Region", district: "Asikuma / Odoben / Brakwa", municipality: "Asikuma" },
  "CC": { region: "Central Region", district: "Cape Coast", municipality: "Cape Coast" },
  "CE": { region: "Central Region", district: "Effutu", municipality: "Effutu" },
  "CF": { region: "Central Region", district: "Ekumfi", municipality: "Ekumfi" },
  "CG": { region: "Central Region", district: "Gomoa East", municipality: "Gomoa East" },
  "CH": { region: "Central Region", district: "Hemang Lower Denkyira", municipality: "Hemang Lower Denkyira" },
  "CI": { region: "Central Region", district: "Gomoa West", municipality: "Gomoa West" },
  "CJ": { region: "Central Region", district: "Ajumako Enyan Esiam", municipality: "Ajumako Enyan Esiam" },
  "CK": { region: "Central Region", district: "Komenda Edina Eguafo", municipality: "Komenda Edina Eguafo" },
  "CL": { region: "Central Region", district: "Gomoa Central", municipality: "Gomoa Central" },
  "CM": { region: "Central Region", district: "Mfantseman", municipality: "Mfantseman" },
  "CN": { region: "Central Region", district: "Assin Central", municipality: "Assin Central" },
  "CO": { region: "Central Region", district: "Agona West", municipality: "Agona West" },
  "CP": { region: "Central Region", district: "Agona East", municipality: "Agona East" },
  "CR": { region: "Central Region", district: "Assin North", municipality: "Assin North" },
  "CS": { region: "Central Region", district: "Assin South", municipality: "Assin South" },
  "CT": { region: "Central Region", district: "Twifo Ati-Morkwa", municipality: "Twifo Ati-Morkwa" },
  "CU": { region: "Central Region", district: "Upper Denkyira East", municipality: "Upper Denkyira East" },
  "CV": { region: "Central Region", district: "Upper Denkyira West", municipality: "Upper Denkyira West" },
  "CW": { region: "Central Region", district: "Awutu Senya West", municipality: "Awutu Senya West" },
  "CX": { region: "Central Region", district: "Awutu Senya East", municipality: "Awutu Senya East" },
  "E2": { region: "Eastern Region", district: "Akuapem North", municipality: "Akuapem North" },
  "E3": { region: "Eastern Region", district: "Akuapem South", municipality: "Akuapem South" },
  "E4": { region: "Eastern Region", district: "Abuakwa North", municipality: "Abuakwa North" },
  "E5": { region: "Eastern Region", district: "Abuakwa South", municipality: "Abuakwa South" },
  "E6": { region: "Eastern Region", district: "Fanteakwa South", municipality: "Fanteakwa South" },
  "E7": { region: "Eastern Region", district: "New Juaben North", municipality: "New Juaben North" },
  "E8": { region: "Eastern Region", district: "Asene Manso Akroso", municipality: "Asene Manso Akroso" },
  "E9": { region: "Eastern Region", district: "Atiwa East", municipality: "Atiwa East" },
  "EA": { region: "Eastern Region", district: "Asuogyaman", municipality: "Asuogyaman" },
  "EB": { region: "Eastern Region", district: "Birim Central", municipality: "Birim Central" },
  "EC": { region: "Eastern Region", district: "Achiase", municipality: "Achiase" },
  "ED": { region: "Eastern Region", district: "Denkyembour", municipality: "Denkyembour" },
  "EF": { region: "Eastern Region", district: "Fanteakwa North", municipality: "Fanteakwa North" },
  "EG": { region: "Eastern Region", district: "Nsawam Adoagyiri", municipality: "Nsawam Adoagyiri" },
  "EH": { region: "Eastern Region", district: "Kwahu East", municipality: "Kwahu East" },
  "EI": { region: "Eastern Region", district: "Kwahu South", municipality: "Kwahu South" },
  "EJ": { region: "Eastern Region", district: "Kwahu West", municipality: "Kwahu West" },
  "EK": { region: "Eastern Region", district: "Kwaebibirem", municipality: "Kwaebibirem" },
  "EL": { region: "Eastern Region", district: "Lower Manya Krobo", municipality: "Lower Manya Krobo" },
  "EM": { region: "Eastern Region", district: "Akyemansa", municipality: "Akyemansa" },
  "EN": { region: "Eastern Region", district: "New Juaben South", municipality: "New Juaben South" },
  "EO": { region: "Eastern Region", district: "Ayensuano", municipality: "Ayensuano" },
  "EP": { region: "Eastern Region", district: "Kwahu Afram Plains North", municipality: "Kwahu Afram Plains North" },
  "EQ": { region: "Eastern Region", district: "Kwahu Afram Plains South", municipality: "Kwahu Afram Plains South" },
  "ER": { region: "Eastern Region", district: "Okere", municipality: "Okere" },
  "ES": { region: "Eastern Region", district: "Suhum", municipality: "Suhum" },
  "ET": { region: "Eastern Region", district: "Atiwa West", municipality: "Atiwa West" },
  "EU": { region: "Eastern Region", district: "Upper Manya Krobo", municipality: "Upper Manya Krobo" },
  "EV": { region: "Eastern Region", district: "Upper West Akim", municipality: "Upper West Akim" },
  "EW": { region: "Eastern Region", district: "West Akim", municipality: "West Akim" },
  "EX": { region: "Eastern Region", district: "Birim North", municipality: "Birim North" },
  "EY": { region: "Eastern Region", district: "Yilo Krobo", municipality: "Yilo Krobo" },
  "EZ": { region: "Eastern Region", district: "Birim South", municipality: "Birim South" },
  "G2": { region: "Greater Accra Region", district: "Ayawaso Central", municipality: "Ayawaso Central" },
  "G3": { region: "Greater Accra Region", district: "Ayawaso North", municipality: "Ayawaso North" },
  "G4": { region: "Greater Accra Region", district: "Ayawaso West", municipality: "Ayawaso West" },
  "G6": { region: "Greater Accra Region", district: "Krowor", municipality: "Krowor" },
  "G7": { region: "Greater Accra Region", district: "Ablekuma Central", municipality: "Ablekuma Central" },
  "GA": { region: "Greater Accra Region", district: "Accra", municipality: "Accra" },
  "GB": { region: "Greater Accra Region", district: "Ashaiman", municipality: "Ashaiman" },
  "GC": { region: "Greater Accra Region", district: "Ga Central", municipality: "Ga Central" },
  "GD": { region: "Greater Accra Region", district: "Adentan", municipality: "Adentan" },
  "GE": { region: "Greater Accra Region", district: "Ga East", municipality: "Ga East" },
  "GF": { region: "Greater Accra Region", district: "Ablekuma North", municipality: "Ablekuma North" },
  "GG": { region: "Greater Accra Region", district: "Ga North", municipality: "Ga North" },
  "GI": { region: "Greater Accra Region", district: "Okaikwei North", municipality: "Okaikwei North" },
  "GJ": { region: "Greater Accra Region", district: "Weija Gbawe", municipality: "Weija Gbawe" },
  "GK": { region: "Greater Accra Region", district: "Kpone Katamanso", municipality: "Kpone Katamanso" },
  "GL": { region: "Greater Accra Region", district: "La Dade Kotopon", municipality: "La Dade Kotopon" },
  "GM": { region: "Greater Accra Region", district: "La Nkwantanang Madina", municipality: "La Nkwantanang Madina" },
  "GN": { region: "Greater Accra Region", district: "Ningo Prampram", municipality: "Ningo Prampram" },
  "GO": { region: "Greater Accra Region", district: "ShaI-Osudoku", municipality: "ShaI-Osudoku" },
  "GQ": { region: "Greater Accra Region", district: "Tema West", municipality: "Tema West" },
  "GR": { region: "Greater Accra Region", district: "Korle Klottey", municipality: "Korle Klottey" },
  "GS": { region: "Greater Accra Region", district: "Ga South", municipality: "Ga South" },
  "GT": { region: "Greater Accra Region", district: "Tema", municipality: "Tema" },
  "GU": { region: "Greater Accra Region", district: "Ablekuma West", municipality: "Ablekuma West" },
  "GV": { region: "Greater Accra Region", district: "Ayawaso East", municipality: "Ayawaso East" },
  "GW": { region: "Greater Accra Region", district: "Ga West", municipality: "Ga West" },
  "GX": { region: "Greater Accra Region", district: "Ada West", municipality: "Ada West" },
  "GY": { region: "Greater Accra Region", district: "Ada East", municipality: "Ada East" },
  "GZ": { region: "Greater Accra Region", district: "Ledzokuku", municipality: "Ledzokuku" },
  "HA": { region: "Ahafo Region", district: "Asunafo North", municipality: "Asunafo North" },
  "HB": { region: "Ahafo Region", district: "Asunafo South", municipality: "Asunafo South" },
  "HQ": { region: "Ahafo Region", district: "Asutifi North", municipality: "Asutifi North" },
  "HR": { region: "Ahafo Region", district: "Asutifi South", municipality: "Asutifi South" },
  "HS": { region: "Ahafo Region", district: "Tano South", municipality: "Tano South" },
  "HT": { region: "Ahafo Region", district: "Tano North", municipality: "Tano North" },
  "MC": { region: "North East Region", district: "Chereponi", municipality: "Chereponi" },
  "ME": { region: "North East Region", district: "East Mamprusi", municipality: "East Mamprusi" },
  "MM": { region: "North East Region", district: "Mamprugu Moaduri", municipality: "Mamprugu Moaduri" },
  "MP": { region: "North East Region", district: "Bunkpurugu Nakpanduri", municipality: "Bunkpurugu Nakpanduri" },
  "MW": { region: "North East Region", district: "West Mamprusi", municipality: "West Mamprusi" },
  "MY": { region: "North East Region", district: "Yunyoo Nasuan", municipality: "Yunyoo Nasuan" },
  "NA": { region: "Northern Region", district: "Kpandai", municipality: "Kpandai" },
  "NF": { region: "Northern Region", district: "Tatale Sangule", municipality: "Tatale Sangule" },
  "NG": { region: "Northern Region", district: "Gushiegu", municipality: "Gushiegu" },
  "NI": { region: "Northern Region", district: "Mion", municipality: "Mion" },
  "NK": { region: "Northern Region", district: "Kumbungu", municipality: "Kumbungu" },
  "NL": { region: "Northern Region", district: "Tolon", municipality: "Tolon" },
  "NN": { region: "Northern Region", district: "Nanumba North", municipality: "Nanumba North" },
  "NO": { region: "Northern Region", district: "Nanumba South", municipality: "Nanumba South" },
  "NR": { region: "Northern Region", district: "Karaga", municipality: "Karaga" },
  "NS": { region: "Northern Region", district: "Sagnerigu", municipality: "Sagnerigu" },
  "NT": { region: "Northern Region", district: "Tamale", municipality: "Tamale" },
  "NU": { region: "Northern Region", district: "Nanton", municipality: "Nanton" },
  "NV": { region: "Northern Region", district: "Savelugu", municipality: "Savelugu" },
  "NX": { region: "Northern Region", district: "Saboba", municipality: "Saboba" },
  "NY": { region: "Northern Region", district: "Yendi", municipality: "Yendi" },
  "NZ": { region: "Northern Region", district: "Zabzugu", municipality: "Zabzugu" },
  "OB": { region: "Oti Region", district: "Biakoye", municipality: "Biakoye" },
  "OE": { region: "Oti Region", district: "Krachi East", municipality: "Krachi East" },
  "OG": { region: "Oti Region", district: "Guan", municipality: "Guan" },
  "OJ": { region: "Oti Region", district: "Jasikan", municipality: "Jasikan" },
  "OK": { region: "Oti Region", district: "Kadjebi", municipality: "Kadjebi" },
  "ON": { region: "Oti Region", district: "Nkwanta North", municipality: "Nkwanta North" },
  "OQ": { region: "Oti Region", district: "Krachi Nchumuru", municipality: "Krachi Nchumuru" },
  "OS": { region: "Oti Region", district: "Nkwanta South", municipality: "Nkwanta South" },
  "OW": { region: "Oti Region", district: "Krachi West", municipality: "Krachi West" },
  "SB": { region: "Savannah Region", district: "BOLE", municipality: "BOLE" },
  "SE": { region: "Savannah Region", district: "EAST GONJA", municipality: "EAST GONJA" },
  "SG": { region: "Savannah Region", district: "CENTRAL GONJA", municipality: "CENTRAL GONJA" },
  "SJ": { region: "Savannah Region", district: "North East Gonja", municipality: "North East Gonja" },
  "SN": { region: "Savannah Region", district: "NORTH GONJA", municipality: "NORTH GONJA" },
  "SS": { region: "Savannah Region", district: "Sawla Tuna Kalba", municipality: "Sawla Tuna Kalba" },
  "SW": { region: "Savannah Region", district: "WEST GONJA", municipality: "WEST GONJA" },
  "TA": { region: "Bono East Region", district: "Atebubu-Amantin", municipality: "Atebubu-Amantin" },
  "TE": { region: "Bono East Region", district: "Sene East", municipality: "Sene East" },
  "TK": { region: "Bono East Region", district: "Kintampo North", municipality: "Kintampo North" },
  "TL": { region: "Bono East Region", district: "Kintampo South", municipality: "Kintampo South" },
  "TN": { region: "Bono East Region", district: "Nkoranza North", municipality: "Nkoranza North" },
  "TO": { region: "Bono East Region", district: "Nkoranza South", municipality: "Nkoranza South" },
  "TP": { region: "Bono East Region", district: "Pru East", municipality: "Pru East" },
  "TS": { region: "Bono East Region", district: "Sene West", municipality: "Sene West" },
  "TT": { region: "Bono East Region", district: "Techiman", municipality: "Techiman" },
  "TW": { region: "Bono East Region", district: "Pru West", municipality: "Pru West" },
  "TX": { region: "Bono East Region", district: "Techiman North", municipality: "Techiman North" },
  "UA": { region: "Upper East Region", district: "Bawku", municipality: "Bawku" },
  "UB": { region: "Upper East Region", district: "Bolgatanga", municipality: "Bolgatanga" },
  "UE": { region: "Upper East Region", district: "Bolgatanga East", municipality: "Bolgatanga East" },
  "UG": { region: "Upper East Region", district: "Garu", municipality: "Garu" },
  "UK": { region: "Upper East Region", district: "Kassena Nankana East", municipality: "Kassena Nankana East" },
  "UL": { region: "Upper East Region", district: "Kassena Nankana West", municipality: "Kassena Nankana West" },
  "UM": { region: "Upper East Region", district: "Tempane", municipality: "Tempane" },
  "UN": { region: "Upper East Region", district: "Nabdam", municipality: "Nabdam" },
  "UO": { region: "Upper East Region", district: "Bongo", municipality: "Bongo" },
  "UP": { region: "Upper East Region", district: "Pusiga", municipality: "Pusiga" },
  "UR": { region: "Upper East Region", district: "Builsa North", municipality: "Builsa North" },
  "US": { region: "Upper East Region", district: "Builsa South", municipality: "Builsa South" },
  "UT": { region: "Upper East Region", district: "Talensi", municipality: "Talensi" },
  "UU": { region: "Upper East Region", district: "Binduri", municipality: "Binduri" },
  "UW": { region: "Upper East Region", district: "Bawku West", municipality: "Bawku West" },
  "VA": { region: "Volta Region", district: "Adaklu", municipality: "Adaklu" },
  "VC": { region: "Volta Region", district: "Hohoe", municipality: "Hohoe" },
  "VD": { region: "Volta Region", district: "North Dayi", municipality: "North Dayi" },
  "VE": { region: "Volta Region", district: "South Dayi", municipality: "South Dayi" },
  "VF": { region: "Volta Region", district: "Afadjato South", municipality: "Afadjato South" },
  "VG": { region: "Volta Region", district: "Agotime Ziope", municipality: "Agotime Ziope" },
  "VH": { region: "Volta Region", district: "Ho", municipality: "Ho" },
  "VI": { region: "Volta Region", district: "Ho West", municipality: "Ho West" },
  "VK": { region: "Volta Region", district: "Keta", municipality: "Keta" },
  "VN": { region: "Volta Region", district: "Anloga", municipality: "Anloga" },
  "VP": { region: "Volta Region", district: "Kpando", municipality: "Kpando" },
  "VT": { region: "Volta Region", district: "North Tongu", municipality: "North Tongu" },
  "VU": { region: "Volta Region", district: "South Tongu", municipality: "South Tongu" },
  "VV": { region: "Volta Region", district: "Central Tongu", municipality: "Central Tongu" },
  "VW": { region: "Volta Region", district: "Akatsi North", municipality: "Akatsi North" },
  "VX": { region: "Volta Region", district: "Akatsi South", municipality: "Akatsi South" },
  "VY": { region: "Volta Region", district: "Ketu North", municipality: "Ketu North" },
  "VZ": { region: "Volta Region", district: "Ketu South", municipality: "Ketu South" },
  "WE": { region: "Western Region", district: "Ellembelle", municipality: "Ellembelle" },
  "WH": { region: "Western Region", district: "Ahanta West", municipality: "Ahanta West" },
  "WJ": { region: "Western Region", district: "Jomoro", municipality: "Jomoro" },
  "WK": { region: "Western Region", district: "Effia Kwesimintim", municipality: "Effia Kwesimintim" },
  "WM": { region: "Western Region", district: "Mpohor", municipality: "Mpohor" },
  "WN": { region: "Western Region", district: "Nzema East", municipality: "Nzema East" },
  "WP": { region: "Western Region", district: "Prestea Huni Valley", municipality: "Prestea Huni Valley" },
  "WR": { region: "Western Region", district: "Shama", municipality: "Shama" },
  "WS": { region: "Western Region", district: "SekondI-Takoradi", municipality: "SekondI-Takoradi" },
  "WT": { region: "Western Region", district: "Tarkwa Nsuaem", municipality: "Tarkwa Nsuaem" },
  "WW": { region: "Western Region", district: "Wassa Amenfi Central", municipality: "Wassa Amenfi Central" },
  "WX": { region: "Western Region", district: "Wassa Amenfi East", municipality: "Wassa Amenfi East" },
  "WY": { region: "Western Region", district: "Wassa Amenfi West", municipality: "Wassa Amenfi West" },
  "WZ": { region: "Western Region", district: "Wassa East", municipality: "Wassa East" },
  "XD": { region: "Upper West Region", district: "Daffiama Bussie Issa", municipality: "Daffiama Bussie Issa" },
  "XJ": { region: "Upper West Region", district: "Jirapa", municipality: "Jirapa" },
  "XK": { region: "Upper West Region", district: "Lambussie Karni", municipality: "Lambussie Karni" },
  "XL": { region: "Upper West Region", district: "Lawra", municipality: "Lawra" },
  "XN": { region: "Upper West Region", district: "Nandom", municipality: "Nandom" },
  "XO": { region: "Upper West Region", district: "Nadowli Kaleo", municipality: "Nadowli Kaleo" },
  "XS": { region: "Upper West Region", district: "Sissala East", municipality: "Sissala East" },
  "XT": { region: "Upper West Region", district: "Sissala West", municipality: "Sissala West" },
  "XW": { region: "Upper West Region", district: "Wa", municipality: "Wa" },
  "XX": { region: "Upper West Region", district: "Wa East", municipality: "Wa East" },
  "XY": { region: "Upper West Region", district: "Wa West", municipality: "Wa West" },
  "YA": { region: "Western North Region", district: "Aowin", municipality: "Aowin" },
  "YB": { region: "Western North Region", district: "Bibiani Anhwiaso Bekwai", municipality: "Bibiani Anhwiaso Bekwai" },
  "YD": { region: "Western North Region", district: "Bodi", municipality: "Bodi" },
  "YE": { region: "Western North Region", district: "Bia East", municipality: "Bia East" },
  "YJ": { region: "Western North Region", district: "Juaboso", municipality: "Juaboso" },
  "YK": { region: "Western North Region", district: "Sefwi Akontombra", municipality: "Sefwi Akontombra" },
  "YS": { region: "Western North Region", district: "Sefwi Wiawso", municipality: "Sefwi Wiawso" },
  "YU": { region: "Western North Region", district: "Suaman", municipality: "Suaman" },
  "YW": { region: "Western North Region", district: "Bia West", municipality: "Bia West" },

};

export function parseGhanaPostPrefix(gps: string): { prefix: string; info: DistrictCodeInfo | null } {
  if (!gps) return { prefix: "", info: null };
  
  const normalized = gps.trim().toUpperCase().replace(/\s/g, "");
  const prefix = normalized.split("-")[0];
  
  if (prefix && GHANA_POST_DISTRICT_CODES[prefix]) {
    return {
      prefix,
      info: GHANA_POST_DISTRICT_CODES[prefix]
    };
  }
  
  // Region fallback based on first character of prefix
  if (prefix && prefix.length >= 1) {
    const firstChar = prefix.charAt(0);
    const regionMap: Record<string, string> = {
      'G': 'Greater Accra Region',
      'A': 'Ashanti Region',
      'C': 'Central Region',
      'E': 'Eastern Region',
      'W': 'Western Region',
      'V': 'Volta Region',
      'N': 'Northern Region',
      'U': 'Upper East Region',
      'X': 'Upper West Region',
      'B': 'Bono Region',
      'T': 'Bono East Region',
      'H': 'Ahafo Region',
      'O': 'Oti Region',
      'S': 'Savannah Region',
      'Y': 'North East Region',
      'Z': 'Western North Region'
    };
    
    if (regionMap[firstChar]) {
      return {
        prefix,
        info: {
          region: regionMap[firstChar],
          district: "Pending Validation",
          municipality: "Unassigned MMDA"
        }
      };
    }
  }
  
  return { prefix, info: null };
}
